version: '3.4'

services:
  word-backend:
    image: xushikuan/go-crawler:${APPLICATION_VERSION}
    env_file:
      - ./sillyhat-env-config/config.env
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 1